[project]
name = "nomes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "kubernetes>=32.0.0",
    "openai>=1.63.0",
]
